chore: updating dependabot to support GHA, TS, JS and docker packages
rajpalc7/aries-acapy-docs pull request #1
Opened 2024-05-21 18:22 UTC by rajpalc7

2024-05-21 18:25 UTC, rajpalc7 commented
Hi @wadeBarnes, this is ready for review now.

2024-05-22 20:42 UTC, WadeBarnes requested changes

2024-05-22 20:42 UTC, WadeBarnes commented on .github/dependabot.yml
> +        update-types: ["version-update:semver-major", "version-update:semver-patch"]
@rajpalc7, I don't see any `npm` dependency manifests in this repository.

2024-05-22 21:03 UTC, WadeBarnes approved these changes

2024-05-22 21:26 UTC, closed without merging